#!/usr/bin/python3

import random
import sys


stars = [".",",", "*"]


def cstars():
    print (random.choice(stars), end=" "*random.randrange(0,12))

sc = 1


if len(sys.argv) == 2:
    sc = int(sys.argv[1])

for i in range(sc):
    cstars()
